from odoo import _, api, fields, models
from datetime import timedelta
from odoo.exceptions import UserError

class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    trucking_trip_id = fields.Many2one(
        'trucking.trip', 
        string="Trip",
        ondelete='cascade',
    )
    trucking_trip_state = fields.Selection(related="trucking_trip_id.state")
    has_trucking_product = fields.Boolean(compute='_compute_has_trucking_product')
    cloned_line_id = fields.Many2one('sale.order.line')
    distance = fields.Float(string="Distance (km)")

    cloned_tms_order_ids = fields.One2many(
        "tms.order",
        "cloned_sale_line_id",
        index=True,
        copy=False,
        help="Transport Order generated by the sales order item",
    )
    
    _sql_constraints = [
        ('trucking_trip_unique', 'unique(trucking_trip_id)', '¡Este viaje ya está asignado a otra línea de pedido!')
    ]
    
    def create(self, vals_list):
        records = super().create(vals_list)
        records_with_trips = records.filtered(lambda L: L.product_id.trucking_trip and not L.trucking_trip_id)
        print("records_with_trips",records_with_trips)
        records_with_trips._create_associated_trip()
            
    def write(self, vals):
        res = super(SaleOrderLine, self).write(vals)

        if 'product_id' in vals:
            for line in self:
                if not line.product_id.trucking_trip and line.trucking_trip_id:
                    line.trucking_trip_id.unlink()
                elif line.product_id.trucking_trip and not line.trucking_trip_id:
                    line._create_associated_trip()
        return res
    
    def _create_associated_trip(self):
        created_trips = self.env['trucking.trip']
        for record in self:
            vals = record._prepare_trucking_values()
            print("creating trip",record, record.order_id,vals)
            trip = record.trucking_trip_id.create([vals])
            record.order_id._post_trip_message(trip)
    
    @api.depends('product_id')
    def _compute_has_trucking_product(self):
        for record in self:
            record.has_trucking_product = record.product_id.trucking_trip
    
    @api.depends('state', 'product_uom_qty', 'qty_delivered', 'qty_to_invoice', 'qty_invoiced', 'trucking_trip_id.state')
    def _compute_invoice_status(self):
        super()._compute_invoice_status()
        for line in self:
            if line.trucking_trip_id:
                if line.trucking_trip_id.state in ['completed', 'cancelled']:
                    line.invoice_status = 'to invoice'
                else:
                    line.invoice_status = 'no'
                print("_compute_invoice_status",line,line.trucking_trip_id.state,line.invoice_status)
                if not line.purchase_line_count:
                    line._purchase_service_generation()
                
    @api.depends('order_id.pricelist_id','product_uom_qty', 'distance')
    def _compute_price_unit(self):
        super()._compute_price_unit()
        print("computed price_unit of ",self,self.mapped('price_unit'))
        
        
    @api.depends('order_id.pricelist_id', 'distance', 'product_uom_qty')
    def _compute_pricelist_item_id(self):
        
        for line in self:
            qty_field=line.order_id.pricelist_id.qty_field or 'product_uom_qty'
            quantity = getattr(line, qty_field ) or 1
            print("checking pricelist_item of",line,"with",qty_field," quantity",quantity)
            line.pricelist_item_id = line.order_id.pricelist_id._get_product_rule(
                line.product_id,
                quantity=quantity,
                date=line._get_order_date(),
            )
            
                
    def _prepare_trucking_values(self, **kwargs):
        """
        Prepare the values to create a new Trucking Trip from a sale order line.
        """
        self.ensure_one()

        return {
            "sale_line_id": self.id,
            "state": 'draft',
            "company_id": self.company_id.id,
            "origin_locality_id": self.order_id.origin_locality_id.id or None,
            "destination_locality_id": self.order_id.destination_locality_id.id or None,
            "commitment_date": self.order_id.commitment_date,
            "distance": self.distance,
        }
    
    def action_open_trucking_trip(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'trucking.trip', 
            'res_id': self.trucking_trip_id.id,
            'view_mode': 'form',
            'target': 'current',
        }
    ### Invoicing methods ###
    
    def _prepare_invoice_line(self, **optional_values):
        ret = super()._prepare_invoice_line(**optional_values)
        print("_prepare_invoice_line",self,self.has_trucking_product,self.trucking_trip_id)
        if self.has_trucking_product and self.trucking_trip_id.cpe_id:
            trip = self.trucking_trip_id
            ret['name']=f'{trip.cpe_id.name}  {trip.origin_locality_id.name.title()} - {trip.destination_locality_id.name.title()}'
        return ret
    
    
    ### Purchase methods ###
    def _purchase_service_generation(self):
        # Remove lines with trucking trip that don't have the driver confirmed.
        lines_with_trip_unconfirmed = self.filtered(lambda l: l.trucking_trip_id and not l.trucking_trip_id.state in ['confirmed','started','arrived','completed'])
        lines_to_process = self-lines_with_trip_unconfirmed
        print("_purchase_service_generation",self,lines_with_trip_unconfirmed)
        return super(SaleOrderLine,lines_to_process)._purchase_service_generation()
    
    def _purchase_service_create(self, quantity=False):
        print("_purchase_service_create",quantity)
        return super()._purchase_service_create(quantity)
    
    def _purchase_service_match_supplier(self, warning=True):
        print("_purchase_service_match_supplier",self, self.trucking_trip_id)
        if self.product_id.trucking_trip and self.trucking_trip_id:
            if self.trucking_trip_id.driver_id:
                print("_purchase_service_match_supplier generating",self.order_id,self.trucking_trip_id.name,self.trucking_trip_id.driver_id)
                driver_id = self.trucking_trip_id.driver_id
                partner_id = driver_id.parent_id or driver_id
                vals = [{
                 'partner_id': partner_id.id,
                 'product_id': self.product_id.id,
                 'product_tmpl_id': self.product_template_id.id,
                 'price': self.price_unit,
                 'min_qty':0,
                }]
                print("_purchase_service_match_supplier creating",self.order_id,partner_id,vals)
                supplier_info =self.env['product.supplierinfo'].create(vals)
                print("_purchase_service_match_supplier created",supplier_info.partner_id,supplier_info.price)
                return supplier_info
            print("_purchase_service_match_supplier MOFO FAILIN'",self.order_id)
            raise UserError(_(
                "Could not generate a trucking purchase for %s since it doesn't "
                "have a driver assigned.",
                self.trucking_trip_id.name
                ))            
        return super()._purchase_service_match_supplier(warning)
    
    def _purchase_service_prepare_line_values(self, purchase_order, quantity=False):
        ret = super()._purchase_service_prepare_line_values(purchase_order, quantity)
        print("_purchase_service_prepare_line_values", ret)
        return ret
        